### PR TITLE
switch to cayman theme

### PR DESCRIPTION
**Pull request by oxapentane**
Initial theme switch done, will copy-paste community links and some boilerplate text right in here in couple of minutes

### CODE REVIEW

**Comment by oxapentane** [comment]
That''s how it looks now. All pages have `draft: true`, since there's no content

image
image

**Comment by Blizter** [comment]
this seems to be less of a headache than creating our own theme from scratch ^^'

**Comment by oxapentane** [comment]
@Blizter I thought of it only as a stopgap while we making something for ourselves. Just so we can be up and running fast. Theoretically switching theme afterwards will be rewriting `config.toml` and maybe some `sed`ing to change front matters if needed.

**Comment by hbjydev** [comment]
We're going to build a Tailwind site (with help from some very nice people over on Slack), which will be deployed as its own theme. I'm going to close this for now, but if we decide to get something up quicker, I'll re-open this again.

**Pull request closed without merging**
